[package]
name        = "alice-bsp-atom-lite"
description = "Board Support Package for M5Atom Lite (ESP32-PICO-D4, Xtensa LX6) with ALICE-RTOS"
keywords    = ["alice", "rtos", "esp32", "m5stack", "no_std"]
categories  = ["embedded", "no-std", "hardware-support"]
version.workspace      = true
edition.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]

[features]
default = []
