[package]
name        = "alice-bsp-atoms3"
description = "Board Support Package for M5Stack AtomS3 (ESP32-S3-PICO-1) with ALICE-RTOS"
keywords    = ["alice", "rtos", "esp32-s3", "m5stack", "no_std"]
categories  = ["embedded", "no-std", "hardware-support"]
version.workspace      = true
edition.workspace      = true
authors.workspace      = true
license.workspace      = true
repository.workspace   = true
rust-version.workspace = true

[dependencies]
alice-rtos = { workspace = true }
esp-hal    = { workspace = true }

[features]
default = []
